// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: service.proto
// Protobuf Java Version: 4.27.2

package com.yxf.serviceframe.entity;

/**
 * <pre>
 * 请求信息
 * </pre>
 *
 * Protobuf type {@code requestInfo}
 */
public final class requestInfo extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:requestInfo)
    requestInfoOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 2,
      /* suffix= */ "",
      requestInfo.class.getName());
  }
  // Use requestInfo.newBuilder() to construct.
  private requestInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private requestInfo() {
    requestId_ = "";
    requestInfo_ = "";
    info_ = "";
    reType_ = 0;
    userId_ = "0";
    devid_ = "";
    reservedInfo_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return Service.internal_static_requestInfo_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return Service.internal_static_requestInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            requestInfo.class, Builder.class);
  }

  private int bitField0_;
  public static final int REQUESTID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile Object requestId_ = "";
  /**
   * <code>required string requestId = 1;</code>
   * @return Whether the requestId field is set.
   */
  @Override
  public boolean hasRequestId() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>required string requestId = 1;</code>
   * @return The requestId.
   */
  @Override
  public String getRequestId() {
    Object ref = requestId_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        requestId_ = s;
      }
      return s;
    }
  }
  /**
   * <code>required string requestId = 1;</code>
   * @return The bytes for requestId.
   */
  @Override
  public com.google.protobuf.ByteString
      getRequestIdBytes() {
    Object ref = requestId_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      requestId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int REQUESTINFO_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile Object requestInfo_ = "";
  /**
   * <code>optional string requestInfo = 2;</code>
   * @return Whether the requestInfo field is set.
   */
  @Override
  public boolean hasRequestInfo() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional string requestInfo = 2;</code>
   * @return The requestInfo.
   */
  @Override
  public String getRequestInfo() {
    Object ref = requestInfo_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        requestInfo_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string requestInfo = 2;</code>
   * @return The bytes for requestInfo.
   */
  @Override
  public com.google.protobuf.ByteString
      getRequestInfoBytes() {
    Object ref = requestInfo_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      requestInfo_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int INFO_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile Object info_ = "";
  /**
   * <code>required string info = 3;</code>
   * @return Whether the info field is set.
   */
  @Override
  public boolean hasInfo() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>required string info = 3;</code>
   * @return The info.
   */
  @Override
  public String getInfo() {
    Object ref = info_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        info_ = s;
      }
      return s;
    }
  }
  /**
   * <code>required string info = 3;</code>
   * @return The bytes for info.
   */
  @Override
  public com.google.protobuf.ByteString
      getInfoBytes() {
    Object ref = info_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      info_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RETYPE_FIELD_NUMBER = 4;
  private int reType_ = 0;
  /**
   * <code>optional .RequestType ReType = 4 [default = SAMPLE];</code>
   * @return Whether the reType field is set.
   */
  @Override public boolean hasReType() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>optional .RequestType ReType = 4 [default = SAMPLE];</code>
   * @return The reType.
   */
  @Override public RequestType getReType() {
    RequestType result = RequestType.forNumber(reType_);
    return result == null ? RequestType.SAMPLE : result;
  }

  public static final int USERID_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile Object userId_ = "0";
  /**
   * <code>optional string userId = 5 [default = "0"];</code>
   * @return Whether the userId field is set.
   */
  @Override
  public boolean hasUserId() {
    return ((bitField0_ & 0x00000010) != 0);
  }
  /**
   * <code>optional string userId = 5 [default = "0"];</code>
   * @return The userId.
   */
  @Override
  public String getUserId() {
    Object ref = userId_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        userId_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string userId = 5 [default = "0"];</code>
   * @return The bytes for userId.
   */
  @Override
  public com.google.protobuf.ByteString
      getUserIdBytes() {
    Object ref = userId_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      userId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DEVID_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private volatile Object devid_ = "";
  /**
   * <code>optional string devid = 6;</code>
   * @return Whether the devid field is set.
   */
  @Override
  public boolean hasDevid() {
    return ((bitField0_ & 0x00000020) != 0);
  }
  /**
   * <code>optional string devid = 6;</code>
   * @return The devid.
   */
  @Override
  public String getDevid() {
    Object ref = devid_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        devid_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string devid = 6;</code>
   * @return The bytes for devid.
   */
  @Override
  public com.google.protobuf.ByteString
      getDevidBytes() {
    Object ref = devid_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      devid_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RESERVEDINFO_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private volatile Object reservedInfo_ = "";
  /**
   * <code>optional string reservedInfo = 7;</code>
   * @return Whether the reservedInfo field is set.
   */
  @Override
  public boolean hasReservedInfo() {
    return ((bitField0_ & 0x00000040) != 0);
  }
  /**
   * <code>optional string reservedInfo = 7;</code>
   * @return The reservedInfo.
   */
  @Override
  public String getReservedInfo() {
    Object ref = reservedInfo_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        reservedInfo_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string reservedInfo = 7;</code>
   * @return The bytes for reservedInfo.
   */
  @Override
  public com.google.protobuf.ByteString
      getReservedInfoBytes() {
    Object ref = reservedInfo_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      reservedInfo_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (!hasRequestId()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasInfo()) {
      memoizedIsInitialized = 0;
      return false;
    }
    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, requestId_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, requestInfo_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, info_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      output.writeEnum(4, reType_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 5, userId_);
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 6, devid_);
    }
    if (((bitField0_ & 0x00000040) != 0)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 7, reservedInfo_);
    }
    getUnknownFields().writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, requestId_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, requestInfo_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, info_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(4, reType_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(5, userId_);
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(6, devid_);
    }
    if (((bitField0_ & 0x00000040) != 0)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(7, reservedInfo_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof requestInfo)) {
      return super.equals(obj);
    }
    requestInfo other = (requestInfo) obj;

    if (hasRequestId() != other.hasRequestId()) return false;
    if (hasRequestId()) {
      if (!getRequestId()
          .equals(other.getRequestId())) return false;
    }
    if (hasRequestInfo() != other.hasRequestInfo()) return false;
    if (hasRequestInfo()) {
      if (!getRequestInfo()
          .equals(other.getRequestInfo())) return false;
    }
    if (hasInfo() != other.hasInfo()) return false;
    if (hasInfo()) {
      if (!getInfo()
          .equals(other.getInfo())) return false;
    }
    if (hasReType() != other.hasReType()) return false;
    if (hasReType()) {
      if (reType_ != other.reType_) return false;
    }
    if (hasUserId() != other.hasUserId()) return false;
    if (hasUserId()) {
      if (!getUserId()
          .equals(other.getUserId())) return false;
    }
    if (hasDevid() != other.hasDevid()) return false;
    if (hasDevid()) {
      if (!getDevid()
          .equals(other.getDevid())) return false;
    }
    if (hasReservedInfo() != other.hasReservedInfo()) return false;
    if (hasReservedInfo()) {
      if (!getReservedInfo()
          .equals(other.getReservedInfo())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasRequestId()) {
      hash = (37 * hash) + REQUESTID_FIELD_NUMBER;
      hash = (53 * hash) + getRequestId().hashCode();
    }
    if (hasRequestInfo()) {
      hash = (37 * hash) + REQUESTINFO_FIELD_NUMBER;
      hash = (53 * hash) + getRequestInfo().hashCode();
    }
    if (hasInfo()) {
      hash = (37 * hash) + INFO_FIELD_NUMBER;
      hash = (53 * hash) + getInfo().hashCode();
    }
    if (hasReType()) {
      hash = (37 * hash) + RETYPE_FIELD_NUMBER;
      hash = (53 * hash) + reType_;
    }
    if (hasUserId()) {
      hash = (37 * hash) + USERID_FIELD_NUMBER;
      hash = (53 * hash) + getUserId().hashCode();
    }
    if (hasDevid()) {
      hash = (37 * hash) + DEVID_FIELD_NUMBER;
      hash = (53 * hash) + getDevid().hashCode();
    }
    if (hasReservedInfo()) {
      hash = (37 * hash) + RESERVEDINFO_FIELD_NUMBER;
      hash = (53 * hash) + getReservedInfo().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static requestInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static requestInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static requestInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static requestInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static requestInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static requestInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static requestInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static requestInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static requestInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static requestInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static requestInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static requestInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(requestInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 请求信息
   * </pre>
   *
   * Protobuf type {@code requestInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:requestInfo)
      requestInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Service.internal_static_requestInfo_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Service.internal_static_requestInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              requestInfo.class, Builder.class);
    }

    // Construct using com.yxf.serviceframe.entity.requestInfo.newBuilder()
    private Builder() {

    }

    private Builder(
        BuilderParent parent) {
      super(parent);

    }
    @Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      requestId_ = "";
      requestInfo_ = "";
      info_ = "";
      reType_ = 0;
      userId_ = "0";
      devid_ = "";
      reservedInfo_ = "";
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return Service.internal_static_requestInfo_descriptor;
    }

    @Override
    public requestInfo getDefaultInstanceForType() {
      return requestInfo.getDefaultInstance();
    }

    @Override
    public requestInfo build() {
      requestInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public requestInfo buildPartial() {
      requestInfo result = new requestInfo(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(requestInfo result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.requestId_ = requestId_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.requestInfo_ = requestInfo_;
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.info_ = info_;
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.reType_ = reType_;
        to_bitField0_ |= 0x00000008;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.userId_ = userId_;
        to_bitField0_ |= 0x00000010;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.devid_ = devid_;
        to_bitField0_ |= 0x00000020;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.reservedInfo_ = reservedInfo_;
        to_bitField0_ |= 0x00000040;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof requestInfo) {
        return mergeFrom((requestInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(requestInfo other) {
      if (other == requestInfo.getDefaultInstance()) return this;
      if (other.hasRequestId()) {
        requestId_ = other.requestId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.hasRequestInfo()) {
        requestInfo_ = other.requestInfo_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.hasInfo()) {
        info_ = other.info_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (other.hasReType()) {
        setReType(other.getReType());
      }
      if (other.hasUserId()) {
        userId_ = other.userId_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (other.hasDevid()) {
        devid_ = other.devid_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      if (other.hasReservedInfo()) {
        reservedInfo_ = other.reservedInfo_;
        bitField0_ |= 0x00000040;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      if (!hasRequestId()) {
        return false;
      }
      if (!hasInfo()) {
        return false;
      }
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              requestId_ = input.readBytes();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              requestInfo_ = input.readBytes();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              info_ = input.readBytes();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 32: {
              int tmpRaw = input.readEnum();
              RequestType tmpValue =
                  RequestType.forNumber(tmpRaw);
              if (tmpValue == null) {
                mergeUnknownVarintField(4, tmpRaw);
              } else {
                reType_ = tmpRaw;
                bitField0_ |= 0x00000008;
              }
              break;
            } // case 32
            case 42: {
              userId_ = input.readBytes();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              devid_ = input.readBytes();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 58: {
              reservedInfo_ = input.readBytes();
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private Object requestId_ = "";
    /**
     * <code>required string requestId = 1;</code>
     * @return Whether the requestId field is set.
     */
    public boolean hasRequestId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required string requestId = 1;</code>
     * @return The requestId.
     */
    public String getRequestId() {
      Object ref = requestId_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          requestId_ = s;
        }
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>required string requestId = 1;</code>
     * @return The bytes for requestId.
     */
    public com.google.protobuf.ByteString
        getRequestIdBytes() {
      Object ref = requestId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        requestId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>required string requestId = 1;</code>
     * @param value The requestId to set.
     * @return This builder for chaining.
     */
    public Builder setRequestId(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      requestId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>required string requestId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearRequestId() {
      requestId_ = getDefaultInstance().getRequestId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>required string requestId = 1;</code>
     * @param value The bytes for requestId to set.
     * @return This builder for chaining.
     */
    public Builder setRequestIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      requestId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private Object requestInfo_ = "";
    /**
     * <code>optional string requestInfo = 2;</code>
     * @return Whether the requestInfo field is set.
     */
    public boolean hasRequestInfo() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string requestInfo = 2;</code>
     * @return The requestInfo.
     */
    public String getRequestInfo() {
      Object ref = requestInfo_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          requestInfo_ = s;
        }
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>optional string requestInfo = 2;</code>
     * @return The bytes for requestInfo.
     */
    public com.google.protobuf.ByteString
        getRequestInfoBytes() {
      Object ref = requestInfo_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        requestInfo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string requestInfo = 2;</code>
     * @param value The requestInfo to set.
     * @return This builder for chaining.
     */
    public Builder setRequestInfo(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      requestInfo_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>optional string requestInfo = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearRequestInfo() {
      requestInfo_ = getDefaultInstance().getRequestInfo();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>optional string requestInfo = 2;</code>
     * @param value The bytes for requestInfo to set.
     * @return This builder for chaining.
     */
    public Builder setRequestInfoBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      requestInfo_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private Object info_ = "";
    /**
     * <code>required string info = 3;</code>
     * @return Whether the info field is set.
     */
    public boolean hasInfo() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>required string info = 3;</code>
     * @return The info.
     */
    public String getInfo() {
      Object ref = info_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          info_ = s;
        }
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>required string info = 3;</code>
     * @return The bytes for info.
     */
    public com.google.protobuf.ByteString
        getInfoBytes() {
      Object ref = info_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        info_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>required string info = 3;</code>
     * @param value The info to set.
     * @return This builder for chaining.
     */
    public Builder setInfo(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      info_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>required string info = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearInfo() {
      info_ = getDefaultInstance().getInfo();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>required string info = 3;</code>
     * @param value The bytes for info to set.
     * @return This builder for chaining.
     */
    public Builder setInfoBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      info_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private int reType_ = 0;
    /**
     * <code>optional .RequestType ReType = 4 [default = SAMPLE];</code>
     * @return Whether the reType field is set.
     */
    @Override public boolean hasReType() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional .RequestType ReType = 4 [default = SAMPLE];</code>
     * @return The reType.
     */
    @Override
    public RequestType getReType() {
      RequestType result = RequestType.forNumber(reType_);
      return result == null ? RequestType.SAMPLE : result;
    }
    /**
     * <code>optional .RequestType ReType = 4 [default = SAMPLE];</code>
     * @param value The reType to set.
     * @return This builder for chaining.
     */
    public Builder setReType(RequestType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000008;
      reType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>optional .RequestType ReType = 4 [default = SAMPLE];</code>
     * @return This builder for chaining.
     */
    public Builder clearReType() {
      bitField0_ = (bitField0_ & ~0x00000008);
      reType_ = 0;
      onChanged();
      return this;
    }

    private Object userId_ = "0";
    /**
     * <code>optional string userId = 5 [default = "0"];</code>
     * @return Whether the userId field is set.
     */
    public boolean hasUserId() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional string userId = 5 [default = "0"];</code>
     * @return The userId.
     */
    public String getUserId() {
      Object ref = userId_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          userId_ = s;
        }
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>optional string userId = 5 [default = "0"];</code>
     * @return The bytes for userId.
     */
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      Object ref = userId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        userId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string userId = 5 [default = "0"];</code>
     * @param value The userId to set.
     * @return This builder for chaining.
     */
    public Builder setUserId(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      userId_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>optional string userId = 5 [default = "0"];</code>
     * @return This builder for chaining.
     */
    public Builder clearUserId() {
      userId_ = getDefaultInstance().getUserId();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <code>optional string userId = 5 [default = "0"];</code>
     * @param value The bytes for userId to set.
     * @return This builder for chaining.
     */
    public Builder setUserIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      userId_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private Object devid_ = "";
    /**
     * <code>optional string devid = 6;</code>
     * @return Whether the devid field is set.
     */
    public boolean hasDevid() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>optional string devid = 6;</code>
     * @return The devid.
     */
    public String getDevid() {
      Object ref = devid_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          devid_ = s;
        }
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>optional string devid = 6;</code>
     * @return The bytes for devid.
     */
    public com.google.protobuf.ByteString
        getDevidBytes() {
      Object ref = devid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        devid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string devid = 6;</code>
     * @param value The devid to set.
     * @return This builder for chaining.
     */
    public Builder setDevid(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      devid_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>optional string devid = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearDevid() {
      devid_ = getDefaultInstance().getDevid();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <code>optional string devid = 6;</code>
     * @param value The bytes for devid to set.
     * @return This builder for chaining.
     */
    public Builder setDevidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      devid_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    private Object reservedInfo_ = "";
    /**
     * <code>optional string reservedInfo = 7;</code>
     * @return Whether the reservedInfo field is set.
     */
    public boolean hasReservedInfo() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>optional string reservedInfo = 7;</code>
     * @return The reservedInfo.
     */
    public String getReservedInfo() {
      Object ref = reservedInfo_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          reservedInfo_ = s;
        }
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>optional string reservedInfo = 7;</code>
     * @return The bytes for reservedInfo.
     */
    public com.google.protobuf.ByteString
        getReservedInfoBytes() {
      Object ref = reservedInfo_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        reservedInfo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string reservedInfo = 7;</code>
     * @param value The reservedInfo to set.
     * @return This builder for chaining.
     */
    public Builder setReservedInfo(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      reservedInfo_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>optional string reservedInfo = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearReservedInfo() {
      reservedInfo_ = getDefaultInstance().getReservedInfo();
      bitField0_ = (bitField0_ & ~0x00000040);
      onChanged();
      return this;
    }
    /**
     * <code>optional string reservedInfo = 7;</code>
     * @param value The bytes for reservedInfo to set.
     * @return This builder for chaining.
     */
    public Builder setReservedInfoBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      reservedInfo_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:requestInfo)
  }

  // @@protoc_insertion_point(class_scope:requestInfo)
  private static final requestInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new requestInfo();
  }

  public static requestInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<requestInfo>
      PARSER = new com.google.protobuf.AbstractParser<requestInfo>() {
    @Override
    public requestInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<requestInfo> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<requestInfo> getParserForType() {
    return PARSER;
  }

  @Override
  public requestInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

