// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: service.proto
// Protobuf Java Version: 4.27.2

package com.yxf.serviceframe.entity;

public interface requestInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:requestInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required string requestId = 1;</code>
   * @return Whether the requestId field is set.
   */
  boolean hasRequestId();
  /**
   * <code>required string requestId = 1;</code>
   * @return The requestId.
   */
  String getRequestId();
  /**
   * <code>required string requestId = 1;</code>
   * @return The bytes for requestId.
   */
  com.google.protobuf.ByteString
      getRequestIdBytes();

  /**
   * <code>optional string requestInfo = 2;</code>
   * @return Whether the requestInfo field is set.
   */
  boolean hasRequestInfo();
  /**
   * <code>optional string requestInfo = 2;</code>
   * @return The requestInfo.
   */
  String getRequestInfo();
  /**
   * <code>optional string requestInfo = 2;</code>
   * @return The bytes for requestInfo.
   */
  com.google.protobuf.ByteString
      getRequestInfoBytes();

  /**
   * <code>required string info = 3;</code>
   * @return Whether the info field is set.
   */
  boolean hasInfo();
  /**
   * <code>required string info = 3;</code>
   * @return The info.
   */
  String getInfo();
  /**
   * <code>required string info = 3;</code>
   * @return The bytes for info.
   */
  com.google.protobuf.ByteString
      getInfoBytes();

  /**
   * <code>optional .RequestType ReType = 4 [default = SAMPLE];</code>
   * @return Whether the reType field is set.
   */
  boolean hasReType();
  /**
   * <code>optional .RequestType ReType = 4 [default = SAMPLE];</code>
   * @return The reType.
   */
  RequestType getReType();

  /**
   * <code>optional string userId = 5 [default = "0"];</code>
   * @return Whether the userId field is set.
   */
  boolean hasUserId();
  /**
   * <code>optional string userId = 5 [default = "0"];</code>
   * @return The userId.
   */
  String getUserId();
  /**
   * <code>optional string userId = 5 [default = "0"];</code>
   * @return The bytes for userId.
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <code>optional string devid = 6;</code>
   * @return Whether the devid field is set.
   */
  boolean hasDevid();
  /**
   * <code>optional string devid = 6;</code>
   * @return The devid.
   */
  String getDevid();
  /**
   * <code>optional string devid = 6;</code>
   * @return The bytes for devid.
   */
  com.google.protobuf.ByteString
      getDevidBytes();

  /**
   * <code>optional string reservedInfo = 7;</code>
   * @return Whether the reservedInfo field is set.
   */
  boolean hasReservedInfo();
  /**
   * <code>optional string reservedInfo = 7;</code>
   * @return The reservedInfo.
   */
  String getReservedInfo();
  /**
   * <code>optional string reservedInfo = 7;</code>
   * @return The bytes for reservedInfo.
   */
  com.google.protobuf.ByteString
      getReservedInfoBytes();
}
