// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: service.proto
// Protobuf Java Version: 4.27.2

package com.yxf.serviceframe.entity;

/**
 * <pre>
 * 结果信息
 * </pre>
 *
 * Protobuf type {@code responseInfo}
 */
public final class responseInfo extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:responseInfo)
    responseInfoOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 2,
      /* suffix= */ "",
      responseInfo.class.getName());
  }
  // Use responseInfo.newBuilder() to construct.
  private responseInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private responseInfo() {
    reponseCode_ = "";
    responseInfo_ = "";
    highlight_ = "";
    reType_ = 0;
    sessionId_ = "";
    userId_ = "";
    itemList_ = java.util.Collections.emptyList();
    reservedInfo_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return Service.internal_static_responseInfo_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return Service.internal_static_responseInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            responseInfo.class, Builder.class);
  }

  /**
   * Protobuf enum {@code responseInfo.itemType}
   */
  public enum itemType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>SAMPLE_TYPE = 0;</code>
     */
    SAMPLE_TYPE(0),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 27,
        /* patch= */ 2,
        /* suffix= */ "",
        itemType.class.getName());
    }
    /**
     * <code>SAMPLE_TYPE = 0;</code>
     */
    public static final int SAMPLE_TYPE_VALUE = 0;


    public final int getNumber() {
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static itemType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static itemType forNumber(int value) {
      switch (value) {
        case 0: return SAMPLE_TYPE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<itemType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        itemType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<itemType>() {
            public itemType findValueByNumber(int number) {
              return itemType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return responseInfo.getDescriptor().getEnumTypes().get(0);
    }

    private static final itemType[] VALUES = values();

    public static itemType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private itemType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:responseInfo.itemType)
  }

  public interface itemInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:responseInfo.itemInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .responseInfo.itemType itemType = 1;</code>
     * @return Whether the itemType field is set.
     */
    boolean hasItemType();
    /**
     * <code>required .responseInfo.itemType itemType = 1;</code>
     * @return The itemType.
     */
    itemType getItemType();

    /**
     * <code>required int64 itemId = 2;</code>
     * @return Whether the itemId field is set.
     */
    boolean hasItemId();
    /**
     * <code>required int64 itemId = 2;</code>
     * @return The itemId.
     */
    long getItemId();

    /**
     * <code>optional string itemFields = 3;</code>
     * @return Whether the itemFields field is set.
     */
    boolean hasItemFields();
    /**
     * <code>optional string itemFields = 3;</code>
     * @return The itemFields.
     */
    String getItemFields();
    /**
     * <code>optional string itemFields = 3;</code>
     * @return The bytes for itemFields.
     */
    com.google.protobuf.ByteString
        getItemFieldsBytes();
  }
  /**
   * Protobuf type {@code responseInfo.itemInfo}
   */
  public static final class itemInfo extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:responseInfo.itemInfo)
      itemInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 27,
        /* patch= */ 2,
        /* suffix= */ "",
        itemInfo.class.getName());
    }
    // Use itemInfo.newBuilder() to construct.
    private itemInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private itemInfo() {
      itemType_ = 0;
      itemFields_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Service.internal_static_responseInfo_itemInfo_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Service.internal_static_responseInfo_itemInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              itemInfo.class, Builder.class);
    }

    private int bitField0_;
    public static final int ITEMTYPE_FIELD_NUMBER = 1;
    private int itemType_ = 0;
    /**
     * <code>required .responseInfo.itemType itemType = 1;</code>
     * @return Whether the itemType field is set.
     */
    @Override public boolean hasItemType() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required .responseInfo.itemType itemType = 1;</code>
     * @return The itemType.
     */
    @Override public itemType getItemType() {
      itemType result = itemType.forNumber(itemType_);
      return result == null ? itemType.SAMPLE_TYPE : result;
    }

    public static final int ITEMID_FIELD_NUMBER = 2;
    private long itemId_ = 0L;
    /**
     * <code>required int64 itemId = 2;</code>
     * @return Whether the itemId field is set.
     */
    @Override
    public boolean hasItemId() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required int64 itemId = 2;</code>
     * @return The itemId.
     */
    @Override
    public long getItemId() {
      return itemId_;
    }

    public static final int ITEMFIELDS_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile Object itemFields_ = "";
    /**
     * <code>optional string itemFields = 3;</code>
     * @return Whether the itemFields field is set.
     */
    @Override
    public boolean hasItemFields() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string itemFields = 3;</code>
     * @return The itemFields.
     */
    @Override
    public String getItemFields() {
      Object ref = itemFields_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          itemFields_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string itemFields = 3;</code>
     * @return The bytes for itemFields.
     */
    @Override
    public com.google.protobuf.ByteString
        getItemFieldsBytes() {
      Object ref = itemFields_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        itemFields_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasItemType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasItemId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeEnum(1, itemType_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt64(2, itemId_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, itemFields_);
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, itemType_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, itemId_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, itemFields_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof itemInfo)) {
        return super.equals(obj);
      }
      itemInfo other = (itemInfo) obj;

      if (hasItemType() != other.hasItemType()) return false;
      if (hasItemType()) {
        if (itemType_ != other.itemType_) return false;
      }
      if (hasItemId() != other.hasItemId()) return false;
      if (hasItemId()) {
        if (getItemId()
            != other.getItemId()) return false;
      }
      if (hasItemFields() != other.hasItemFields()) return false;
      if (hasItemFields()) {
        if (!getItemFields()
            .equals(other.getItemFields())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasItemType()) {
        hash = (37 * hash) + ITEMTYPE_FIELD_NUMBER;
        hash = (53 * hash) + itemType_;
      }
      if (hasItemId()) {
        hash = (37 * hash) + ITEMID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getItemId());
      }
      if (hasItemFields()) {
        hash = (37 * hash) + ITEMFIELDS_FIELD_NUMBER;
        hash = (53 * hash) + getItemFields().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static itemInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static itemInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static itemInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static itemInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static itemInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static itemInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static itemInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static itemInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static itemInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static itemInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static itemInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static itemInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(itemInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code responseInfo.itemInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:responseInfo.itemInfo)
        itemInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Service.internal_static_responseInfo_itemInfo_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Service.internal_static_responseInfo_itemInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                itemInfo.class, Builder.class);
      }

      // Construct using com.yxf.serviceframe.entity.responseInfo.itemInfo.newBuilder()
      private Builder() {

      }

      private Builder(
          BuilderParent parent) {
        super(parent);

      }
      @Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        itemType_ = 0;
        itemId_ = 0L;
        itemFields_ = "";
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Service.internal_static_responseInfo_itemInfo_descriptor;
      }

      @Override
      public itemInfo getDefaultInstanceForType() {
        return itemInfo.getDefaultInstance();
      }

      @Override
      public itemInfo build() {
        itemInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public itemInfo buildPartial() {
        itemInfo result = new itemInfo(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(itemInfo result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.itemType_ = itemType_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.itemId_ = itemId_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.itemFields_ = itemFields_;
          to_bitField0_ |= 0x00000004;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof itemInfo) {
          return mergeFrom((itemInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(itemInfo other) {
        if (other == itemInfo.getDefaultInstance()) return this;
        if (other.hasItemType()) {
          setItemType(other.getItemType());
        }
        if (other.hasItemId()) {
          setItemId(other.getItemId());
        }
        if (other.hasItemFields()) {
          itemFields_ = other.itemFields_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        if (!hasItemType()) {
          return false;
        }
        if (!hasItemId()) {
          return false;
        }
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                int tmpRaw = input.readEnum();
                itemType tmpValue =
                    itemType.forNumber(tmpRaw);
                if (tmpValue == null) {
                  mergeUnknownVarintField(1, tmpRaw);
                } else {
                  itemType_ = tmpRaw;
                  bitField0_ |= 0x00000001;
                }
                break;
              } // case 8
              case 16: {
                itemId_ = input.readInt64();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 26: {
                itemFields_ = input.readBytes();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int itemType_ = 0;
      /**
       * <code>required .responseInfo.itemType itemType = 1;</code>
       * @return Whether the itemType field is set.
       */
      @Override public boolean hasItemType() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required .responseInfo.itemType itemType = 1;</code>
       * @return The itemType.
       */
      @Override
      public itemType getItemType() {
        itemType result = itemType.forNumber(itemType_);
        return result == null ? itemType.SAMPLE_TYPE : result;
      }
      /**
       * <code>required .responseInfo.itemType itemType = 1;</code>
       * @param value The itemType to set.
       * @return This builder for chaining.
       */
      public Builder setItemType(itemType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        itemType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>required .responseInfo.itemType itemType = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearItemType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        itemType_ = 0;
        onChanged();
        return this;
      }

      private long itemId_ ;
      /**
       * <code>required int64 itemId = 2;</code>
       * @return Whether the itemId field is set.
       */
      @Override
      public boolean hasItemId() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required int64 itemId = 2;</code>
       * @return The itemId.
       */
      @Override
      public long getItemId() {
        return itemId_;
      }
      /**
       * <code>required int64 itemId = 2;</code>
       * @param value The itemId to set.
       * @return This builder for chaining.
       */
      public Builder setItemId(long value) {

        itemId_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 itemId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearItemId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        itemId_ = 0L;
        onChanged();
        return this;
      }

      private Object itemFields_ = "";
      /**
       * <code>optional string itemFields = 3;</code>
       * @return Whether the itemFields field is set.
       */
      public boolean hasItemFields() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional string itemFields = 3;</code>
       * @return The itemFields.
       */
      public String getItemFields() {
        Object ref = itemFields_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            itemFields_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string itemFields = 3;</code>
       * @return The bytes for itemFields.
       */
      public com.google.protobuf.ByteString
          getItemFieldsBytes() {
        Object ref = itemFields_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          itemFields_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string itemFields = 3;</code>
       * @param value The itemFields to set.
       * @return This builder for chaining.
       */
      public Builder setItemFields(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        itemFields_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>optional string itemFields = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearItemFields() {
        itemFields_ = getDefaultInstance().getItemFields();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>optional string itemFields = 3;</code>
       * @param value The bytes for itemFields to set.
       * @return This builder for chaining.
       */
      public Builder setItemFieldsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        itemFields_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:responseInfo.itemInfo)
    }

    // @@protoc_insertion_point(class_scope:responseInfo.itemInfo)
    private static final itemInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new itemInfo();
    }

    public static itemInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<itemInfo>
        PARSER = new com.google.protobuf.AbstractParser<itemInfo>() {
      @Override
      public itemInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<itemInfo> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<itemInfo> getParserForType() {
      return PARSER;
    }

    @Override
    public itemInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private int bitField0_;
  public static final int REPONSECODE_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile Object reponseCode_ = "";
  /**
   * <code>required string reponseCode = 1;</code>
   * @return Whether the reponseCode field is set.
   */
  @Override
  public boolean hasReponseCode() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>required string reponseCode = 1;</code>
   * @return The reponseCode.
   */
  @Override
  public String getReponseCode() {
    Object ref = reponseCode_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        reponseCode_ = s;
      }
      return s;
    }
  }
  /**
   * <code>required string reponseCode = 1;</code>
   * @return The bytes for reponseCode.
   */
  @Override
  public com.google.protobuf.ByteString
      getReponseCodeBytes() {
    Object ref = reponseCode_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      reponseCode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RESPONSEINFO_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile Object responseInfo_ = "";
  /**
   * <code>optional string responseInfo = 2;</code>
   * @return Whether the responseInfo field is set.
   */
  @Override
  public boolean hasResponseInfo() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional string responseInfo = 2;</code>
   * @return The responseInfo.
   */
  @Override
  public String getResponseInfo() {
    Object ref = responseInfo_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        responseInfo_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string responseInfo = 2;</code>
   * @return The bytes for responseInfo.
   */
  @Override
  public com.google.protobuf.ByteString
      getResponseInfoBytes() {
    Object ref = responseInfo_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      responseInfo_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int HIGHLIGHT_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile Object highlight_ = "";
  /**
   * <code>optional string highlight = 3;</code>
   * @return Whether the highlight field is set.
   */
  @Override
  public boolean hasHighlight() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional string highlight = 3;</code>
   * @return The highlight.
   */
  @Override
  public String getHighlight() {
    Object ref = highlight_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        highlight_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string highlight = 3;</code>
   * @return The bytes for highlight.
   */
  @Override
  public com.google.protobuf.ByteString
      getHighlightBytes() {
    Object ref = highlight_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      highlight_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RETYPE_FIELD_NUMBER = 4;
  private int reType_ = 0;
  /**
   * <code>required .RequestType ReType = 4 [default = SAMPLE];</code>
   * @return Whether the reType field is set.
   */
  @Override public boolean hasReType() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>required .RequestType ReType = 4 [default = SAMPLE];</code>
   * @return The reType.
   */
  @Override public RequestType getReType() {
    RequestType result = RequestType.forNumber(reType_);
    return result == null ? RequestType.SAMPLE : result;
  }

  public static final int SESSIONID_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile Object sessionId_ = "";
  /**
   * <code>required string sessionId = 5;</code>
   * @return Whether the sessionId field is set.
   */
  @Override
  public boolean hasSessionId() {
    return ((bitField0_ & 0x00000010) != 0);
  }
  /**
   * <code>required string sessionId = 5;</code>
   * @return The sessionId.
   */
  @Override
  public String getSessionId() {
    Object ref = sessionId_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        sessionId_ = s;
      }
      return s;
    }
  }
  /**
   * <code>required string sessionId = 5;</code>
   * @return The bytes for sessionId.
   */
  @Override
  public com.google.protobuf.ByteString
      getSessionIdBytes() {
    Object ref = sessionId_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      sessionId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int USERID_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private volatile Object userId_ = "";
  /**
   * <code>optional string userId = 6;</code>
   * @return Whether the userId field is set.
   */
  @Override
  public boolean hasUserId() {
    return ((bitField0_ & 0x00000020) != 0);
  }
  /**
   * <code>optional string userId = 6;</code>
   * @return The userId.
   */
  @Override
  public String getUserId() {
    Object ref = userId_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        userId_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string userId = 6;</code>
   * @return The bytes for userId.
   */
  @Override
  public com.google.protobuf.ByteString
      getUserIdBytes() {
    Object ref = userId_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      userId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ITEMLIST_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private java.util.List<itemInfo> itemList_;
  /**
   * <code>repeated .responseInfo.itemInfo itemList = 7;</code>
   */
  @Override
  public java.util.List<itemInfo> getItemListList() {
    return itemList_;
  }
  /**
   * <code>repeated .responseInfo.itemInfo itemList = 7;</code>
   */
  @Override
  public java.util.List<? extends itemInfoOrBuilder>
      getItemListOrBuilderList() {
    return itemList_;
  }
  /**
   * <code>repeated .responseInfo.itemInfo itemList = 7;</code>
   */
  @Override
  public int getItemListCount() {
    return itemList_.size();
  }
  /**
   * <code>repeated .responseInfo.itemInfo itemList = 7;</code>
   */
  @Override
  public itemInfo getItemList(int index) {
    return itemList_.get(index);
  }
  /**
   * <code>repeated .responseInfo.itemInfo itemList = 7;</code>
   */
  @Override
  public itemInfoOrBuilder getItemListOrBuilder(
      int index) {
    return itemList_.get(index);
  }

  public static final int RESERVEDINFO_FIELD_NUMBER = 8;
  @SuppressWarnings("serial")
  private volatile Object reservedInfo_ = "";
  /**
   * <code>optional string reservedInfo = 8;</code>
   * @return Whether the reservedInfo field is set.
   */
  @Override
  public boolean hasReservedInfo() {
    return ((bitField0_ & 0x00000040) != 0);
  }
  /**
   * <code>optional string reservedInfo = 8;</code>
   * @return The reservedInfo.
   */
  @Override
  public String getReservedInfo() {
    Object ref = reservedInfo_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        reservedInfo_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string reservedInfo = 8;</code>
   * @return The bytes for reservedInfo.
   */
  @Override
  public com.google.protobuf.ByteString
      getReservedInfoBytes() {
    Object ref = reservedInfo_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      reservedInfo_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (!hasReponseCode()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasReType()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasSessionId()) {
      memoizedIsInitialized = 0;
      return false;
    }
    for (int i = 0; i < getItemListCount(); i++) {
      if (!getItemList(i).isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
    }
    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, reponseCode_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, responseInfo_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, highlight_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      output.writeEnum(4, reType_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 5, sessionId_);
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 6, userId_);
    }
    for (int i = 0; i < itemList_.size(); i++) {
      output.writeMessage(7, itemList_.get(i));
    }
    if (((bitField0_ & 0x00000040) != 0)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 8, reservedInfo_);
    }
    getUnknownFields().writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, reponseCode_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, responseInfo_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, highlight_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(4, reType_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(5, sessionId_);
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(6, userId_);
    }
    for (int i = 0; i < itemList_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, itemList_.get(i));
    }
    if (((bitField0_ & 0x00000040) != 0)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(8, reservedInfo_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof responseInfo)) {
      return super.equals(obj);
    }
    responseInfo other = (responseInfo) obj;

    if (hasReponseCode() != other.hasReponseCode()) return false;
    if (hasReponseCode()) {
      if (!getReponseCode()
          .equals(other.getReponseCode())) return false;
    }
    if (hasResponseInfo() != other.hasResponseInfo()) return false;
    if (hasResponseInfo()) {
      if (!getResponseInfo()
          .equals(other.getResponseInfo())) return false;
    }
    if (hasHighlight() != other.hasHighlight()) return false;
    if (hasHighlight()) {
      if (!getHighlight()
          .equals(other.getHighlight())) return false;
    }
    if (hasReType() != other.hasReType()) return false;
    if (hasReType()) {
      if (reType_ != other.reType_) return false;
    }
    if (hasSessionId() != other.hasSessionId()) return false;
    if (hasSessionId()) {
      if (!getSessionId()
          .equals(other.getSessionId())) return false;
    }
    if (hasUserId() != other.hasUserId()) return false;
    if (hasUserId()) {
      if (!getUserId()
          .equals(other.getUserId())) return false;
    }
    if (!getItemListList()
        .equals(other.getItemListList())) return false;
    if (hasReservedInfo() != other.hasReservedInfo()) return false;
    if (hasReservedInfo()) {
      if (!getReservedInfo()
          .equals(other.getReservedInfo())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasReponseCode()) {
      hash = (37 * hash) + REPONSECODE_FIELD_NUMBER;
      hash = (53 * hash) + getReponseCode().hashCode();
    }
    if (hasResponseInfo()) {
      hash = (37 * hash) + RESPONSEINFO_FIELD_NUMBER;
      hash = (53 * hash) + getResponseInfo().hashCode();
    }
    if (hasHighlight()) {
      hash = (37 * hash) + HIGHLIGHT_FIELD_NUMBER;
      hash = (53 * hash) + getHighlight().hashCode();
    }
    if (hasReType()) {
      hash = (37 * hash) + RETYPE_FIELD_NUMBER;
      hash = (53 * hash) + reType_;
    }
    if (hasSessionId()) {
      hash = (37 * hash) + SESSIONID_FIELD_NUMBER;
      hash = (53 * hash) + getSessionId().hashCode();
    }
    if (hasUserId()) {
      hash = (37 * hash) + USERID_FIELD_NUMBER;
      hash = (53 * hash) + getUserId().hashCode();
    }
    if (getItemListCount() > 0) {
      hash = (37 * hash) + ITEMLIST_FIELD_NUMBER;
      hash = (53 * hash) + getItemListList().hashCode();
    }
    if (hasReservedInfo()) {
      hash = (37 * hash) + RESERVEDINFO_FIELD_NUMBER;
      hash = (53 * hash) + getReservedInfo().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static responseInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static responseInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static responseInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static responseInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static responseInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static responseInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static responseInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static responseInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static responseInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static responseInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static responseInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static responseInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(responseInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 结果信息
   * </pre>
   *
   * Protobuf type {@code responseInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:responseInfo)
      responseInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Service.internal_static_responseInfo_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Service.internal_static_responseInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              responseInfo.class, Builder.class);
    }

    // Construct using com.yxf.serviceframe.entity.responseInfo.newBuilder()
    private Builder() {

    }

    private Builder(
        BuilderParent parent) {
      super(parent);

    }
    @Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      reponseCode_ = "";
      responseInfo_ = "";
      highlight_ = "";
      reType_ = 0;
      sessionId_ = "";
      userId_ = "";
      if (itemListBuilder_ == null) {
        itemList_ = java.util.Collections.emptyList();
      } else {
        itemList_ = null;
        itemListBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000040);
      reservedInfo_ = "";
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return Service.internal_static_responseInfo_descriptor;
    }

    @Override
    public responseInfo getDefaultInstanceForType() {
      return responseInfo.getDefaultInstance();
    }

    @Override
    public responseInfo build() {
      responseInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public responseInfo buildPartial() {
      responseInfo result = new responseInfo(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(responseInfo result) {
      if (itemListBuilder_ == null) {
        if (((bitField0_ & 0x00000040) != 0)) {
          itemList_ = java.util.Collections.unmodifiableList(itemList_);
          bitField0_ = (bitField0_ & ~0x00000040);
        }
        result.itemList_ = itemList_;
      } else {
        result.itemList_ = itemListBuilder_.build();
      }
    }

    private void buildPartial0(responseInfo result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.reponseCode_ = reponseCode_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.responseInfo_ = responseInfo_;
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.highlight_ = highlight_;
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.reType_ = reType_;
        to_bitField0_ |= 0x00000008;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.sessionId_ = sessionId_;
        to_bitField0_ |= 0x00000010;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.userId_ = userId_;
        to_bitField0_ |= 0x00000020;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.reservedInfo_ = reservedInfo_;
        to_bitField0_ |= 0x00000040;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof responseInfo) {
        return mergeFrom((responseInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(responseInfo other) {
      if (other == responseInfo.getDefaultInstance()) return this;
      if (other.hasReponseCode()) {
        reponseCode_ = other.reponseCode_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.hasResponseInfo()) {
        responseInfo_ = other.responseInfo_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.hasHighlight()) {
        highlight_ = other.highlight_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (other.hasReType()) {
        setReType(other.getReType());
      }
      if (other.hasSessionId()) {
        sessionId_ = other.sessionId_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (other.hasUserId()) {
        userId_ = other.userId_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      if (itemListBuilder_ == null) {
        if (!other.itemList_.isEmpty()) {
          if (itemList_.isEmpty()) {
            itemList_ = other.itemList_;
            bitField0_ = (bitField0_ & ~0x00000040);
          } else {
            ensureItemListIsMutable();
            itemList_.addAll(other.itemList_);
          }
          onChanged();
        }
      } else {
        if (!other.itemList_.isEmpty()) {
          if (itemListBuilder_.isEmpty()) {
            itemListBuilder_.dispose();
            itemListBuilder_ = null;
            itemList_ = other.itemList_;
            bitField0_ = (bitField0_ & ~0x00000040);
            itemListBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getItemListFieldBuilder() : null;
          } else {
            itemListBuilder_.addAllMessages(other.itemList_);
          }
        }
      }
      if (other.hasReservedInfo()) {
        reservedInfo_ = other.reservedInfo_;
        bitField0_ |= 0x00000080;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      if (!hasReponseCode()) {
        return false;
      }
      if (!hasReType()) {
        return false;
      }
      if (!hasSessionId()) {
        return false;
      }
      for (int i = 0; i < getItemListCount(); i++) {
        if (!getItemList(i).isInitialized()) {
          return false;
        }
      }
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              reponseCode_ = input.readBytes();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              responseInfo_ = input.readBytes();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              highlight_ = input.readBytes();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 32: {
              int tmpRaw = input.readEnum();
              RequestType tmpValue =
                  RequestType.forNumber(tmpRaw);
              if (tmpValue == null) {
                mergeUnknownVarintField(4, tmpRaw);
              } else {
                reType_ = tmpRaw;
                bitField0_ |= 0x00000008;
              }
              break;
            } // case 32
            case 42: {
              sessionId_ = input.readBytes();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              userId_ = input.readBytes();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 58: {
              itemInfo m =
                  input.readMessage(
                      itemInfo.parser(),
                      extensionRegistry);
              if (itemListBuilder_ == null) {
                ensureItemListIsMutable();
                itemList_.add(m);
              } else {
                itemListBuilder_.addMessage(m);
              }
              break;
            } // case 58
            case 66: {
              reservedInfo_ = input.readBytes();
              bitField0_ |= 0x00000080;
              break;
            } // case 66
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private Object reponseCode_ = "";
    /**
     * <code>required string reponseCode = 1;</code>
     * @return Whether the reponseCode field is set.
     */
    public boolean hasReponseCode() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required string reponseCode = 1;</code>
     * @return The reponseCode.
     */
    public String getReponseCode() {
      Object ref = reponseCode_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          reponseCode_ = s;
        }
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>required string reponseCode = 1;</code>
     * @return The bytes for reponseCode.
     */
    public com.google.protobuf.ByteString
        getReponseCodeBytes() {
      Object ref = reponseCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        reponseCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>required string reponseCode = 1;</code>
     * @param value The reponseCode to set.
     * @return This builder for chaining.
     */
    public Builder setReponseCode(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      reponseCode_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>required string reponseCode = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearReponseCode() {
      reponseCode_ = getDefaultInstance().getReponseCode();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>required string reponseCode = 1;</code>
     * @param value The bytes for reponseCode to set.
     * @return This builder for chaining.
     */
    public Builder setReponseCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      reponseCode_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private Object responseInfo_ = "";
    /**
     * <code>optional string responseInfo = 2;</code>
     * @return Whether the responseInfo field is set.
     */
    public boolean hasResponseInfo() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string responseInfo = 2;</code>
     * @return The responseInfo.
     */
    public String getResponseInfo() {
      Object ref = responseInfo_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          responseInfo_ = s;
        }
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>optional string responseInfo = 2;</code>
     * @return The bytes for responseInfo.
     */
    public com.google.protobuf.ByteString
        getResponseInfoBytes() {
      Object ref = responseInfo_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        responseInfo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string responseInfo = 2;</code>
     * @param value The responseInfo to set.
     * @return This builder for chaining.
     */
    public Builder setResponseInfo(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      responseInfo_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>optional string responseInfo = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearResponseInfo() {
      responseInfo_ = getDefaultInstance().getResponseInfo();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>optional string responseInfo = 2;</code>
     * @param value The bytes for responseInfo to set.
     * @return This builder for chaining.
     */
    public Builder setResponseInfoBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      responseInfo_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private Object highlight_ = "";
    /**
     * <code>optional string highlight = 3;</code>
     * @return Whether the highlight field is set.
     */
    public boolean hasHighlight() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string highlight = 3;</code>
     * @return The highlight.
     */
    public String getHighlight() {
      Object ref = highlight_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          highlight_ = s;
        }
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>optional string highlight = 3;</code>
     * @return The bytes for highlight.
     */
    public com.google.protobuf.ByteString
        getHighlightBytes() {
      Object ref = highlight_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        highlight_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string highlight = 3;</code>
     * @param value The highlight to set.
     * @return This builder for chaining.
     */
    public Builder setHighlight(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      highlight_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>optional string highlight = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearHighlight() {
      highlight_ = getDefaultInstance().getHighlight();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>optional string highlight = 3;</code>
     * @param value The bytes for highlight to set.
     * @return This builder for chaining.
     */
    public Builder setHighlightBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      highlight_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private int reType_ = 0;
    /**
     * <code>required .RequestType ReType = 4 [default = SAMPLE];</code>
     * @return Whether the reType field is set.
     */
    @Override public boolean hasReType() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>required .RequestType ReType = 4 [default = SAMPLE];</code>
     * @return The reType.
     */
    @Override
    public RequestType getReType() {
      RequestType result = RequestType.forNumber(reType_);
      return result == null ? RequestType.SAMPLE : result;
    }
    /**
     * <code>required .RequestType ReType = 4 [default = SAMPLE];</code>
     * @param value The reType to set.
     * @return This builder for chaining.
     */
    public Builder setReType(RequestType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000008;
      reType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>required .RequestType ReType = 4 [default = SAMPLE];</code>
     * @return This builder for chaining.
     */
    public Builder clearReType() {
      bitField0_ = (bitField0_ & ~0x00000008);
      reType_ = 0;
      onChanged();
      return this;
    }

    private Object sessionId_ = "";
    /**
     * <code>required string sessionId = 5;</code>
     * @return Whether the sessionId field is set.
     */
    public boolean hasSessionId() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>required string sessionId = 5;</code>
     * @return The sessionId.
     */
    public String getSessionId() {
      Object ref = sessionId_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          sessionId_ = s;
        }
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>required string sessionId = 5;</code>
     * @return The bytes for sessionId.
     */
    public com.google.protobuf.ByteString
        getSessionIdBytes() {
      Object ref = sessionId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        sessionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>required string sessionId = 5;</code>
     * @param value The sessionId to set.
     * @return This builder for chaining.
     */
    public Builder setSessionId(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      sessionId_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>required string sessionId = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearSessionId() {
      sessionId_ = getDefaultInstance().getSessionId();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <code>required string sessionId = 5;</code>
     * @param value The bytes for sessionId to set.
     * @return This builder for chaining.
     */
    public Builder setSessionIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      sessionId_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private Object userId_ = "";
    /**
     * <code>optional string userId = 6;</code>
     * @return Whether the userId field is set.
     */
    public boolean hasUserId() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>optional string userId = 6;</code>
     * @return The userId.
     */
    public String getUserId() {
      Object ref = userId_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          userId_ = s;
        }
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>optional string userId = 6;</code>
     * @return The bytes for userId.
     */
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      Object ref = userId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        userId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string userId = 6;</code>
     * @param value The userId to set.
     * @return This builder for chaining.
     */
    public Builder setUserId(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      userId_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>optional string userId = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearUserId() {
      userId_ = getDefaultInstance().getUserId();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <code>optional string userId = 6;</code>
     * @param value The bytes for userId to set.
     * @return This builder for chaining.
     */
    public Builder setUserIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      userId_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    private java.util.List<itemInfo> itemList_ =
      java.util.Collections.emptyList();
    private void ensureItemListIsMutable() {
      if (!((bitField0_ & 0x00000040) != 0)) {
        itemList_ = new java.util.ArrayList<itemInfo>(itemList_);
        bitField0_ |= 0x00000040;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        itemInfo, itemInfo.Builder, itemInfoOrBuilder> itemListBuilder_;

    /**
     * <code>repeated .responseInfo.itemInfo itemList = 7;</code>
     */
    public java.util.List<itemInfo> getItemListList() {
      if (itemListBuilder_ == null) {
        return java.util.Collections.unmodifiableList(itemList_);
      } else {
        return itemListBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .responseInfo.itemInfo itemList = 7;</code>
     */
    public int getItemListCount() {
      if (itemListBuilder_ == null) {
        return itemList_.size();
      } else {
        return itemListBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .responseInfo.itemInfo itemList = 7;</code>
     */
    public itemInfo getItemList(int index) {
      if (itemListBuilder_ == null) {
        return itemList_.get(index);
      } else {
        return itemListBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .responseInfo.itemInfo itemList = 7;</code>
     */
    public Builder setItemList(
        int index, itemInfo value) {
      if (itemListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureItemListIsMutable();
        itemList_.set(index, value);
        onChanged();
      } else {
        itemListBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .responseInfo.itemInfo itemList = 7;</code>
     */
    public Builder setItemList(
        int index, itemInfo.Builder builderForValue) {
      if (itemListBuilder_ == null) {
        ensureItemListIsMutable();
        itemList_.set(index, builderForValue.build());
        onChanged();
      } else {
        itemListBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .responseInfo.itemInfo itemList = 7;</code>
     */
    public Builder addItemList(itemInfo value) {
      if (itemListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureItemListIsMutable();
        itemList_.add(value);
        onChanged();
      } else {
        itemListBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .responseInfo.itemInfo itemList = 7;</code>
     */
    public Builder addItemList(
        int index, itemInfo value) {
      if (itemListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureItemListIsMutable();
        itemList_.add(index, value);
        onChanged();
      } else {
        itemListBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .responseInfo.itemInfo itemList = 7;</code>
     */
    public Builder addItemList(
        itemInfo.Builder builderForValue) {
      if (itemListBuilder_ == null) {
        ensureItemListIsMutable();
        itemList_.add(builderForValue.build());
        onChanged();
      } else {
        itemListBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .responseInfo.itemInfo itemList = 7;</code>
     */
    public Builder addItemList(
        int index, itemInfo.Builder builderForValue) {
      if (itemListBuilder_ == null) {
        ensureItemListIsMutable();
        itemList_.add(index, builderForValue.build());
        onChanged();
      } else {
        itemListBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .responseInfo.itemInfo itemList = 7;</code>
     */
    public Builder addAllItemList(
        Iterable<? extends itemInfo> values) {
      if (itemListBuilder_ == null) {
        ensureItemListIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, itemList_);
        onChanged();
      } else {
        itemListBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .responseInfo.itemInfo itemList = 7;</code>
     */
    public Builder clearItemList() {
      if (itemListBuilder_ == null) {
        itemList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000040);
        onChanged();
      } else {
        itemListBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .responseInfo.itemInfo itemList = 7;</code>
     */
    public Builder removeItemList(int index) {
      if (itemListBuilder_ == null) {
        ensureItemListIsMutable();
        itemList_.remove(index);
        onChanged();
      } else {
        itemListBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .responseInfo.itemInfo itemList = 7;</code>
     */
    public itemInfo.Builder getItemListBuilder(
        int index) {
      return getItemListFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .responseInfo.itemInfo itemList = 7;</code>
     */
    public itemInfoOrBuilder getItemListOrBuilder(
        int index) {
      if (itemListBuilder_ == null) {
        return itemList_.get(index);  } else {
        return itemListBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .responseInfo.itemInfo itemList = 7;</code>
     */
    public java.util.List<? extends itemInfoOrBuilder>
         getItemListOrBuilderList() {
      if (itemListBuilder_ != null) {
        return itemListBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(itemList_);
      }
    }
    /**
     * <code>repeated .responseInfo.itemInfo itemList = 7;</code>
     */
    public itemInfo.Builder addItemListBuilder() {
      return getItemListFieldBuilder().addBuilder(
          itemInfo.getDefaultInstance());
    }
    /**
     * <code>repeated .responseInfo.itemInfo itemList = 7;</code>
     */
    public itemInfo.Builder addItemListBuilder(
        int index) {
      return getItemListFieldBuilder().addBuilder(
          index, itemInfo.getDefaultInstance());
    }
    /**
     * <code>repeated .responseInfo.itemInfo itemList = 7;</code>
     */
    public java.util.List<itemInfo.Builder>
         getItemListBuilderList() {
      return getItemListFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        itemInfo, itemInfo.Builder, itemInfoOrBuilder>
        getItemListFieldBuilder() {
      if (itemListBuilder_ == null) {
        itemListBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            itemInfo, itemInfo.Builder, itemInfoOrBuilder>(
                itemList_,
                ((bitField0_ & 0x00000040) != 0),
                getParentForChildren(),
                isClean());
        itemList_ = null;
      }
      return itemListBuilder_;
    }

    private Object reservedInfo_ = "";
    /**
     * <code>optional string reservedInfo = 8;</code>
     * @return Whether the reservedInfo field is set.
     */
    public boolean hasReservedInfo() {
      return ((bitField0_ & 0x00000080) != 0);
    }
    /**
     * <code>optional string reservedInfo = 8;</code>
     * @return The reservedInfo.
     */
    public String getReservedInfo() {
      Object ref = reservedInfo_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          reservedInfo_ = s;
        }
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>optional string reservedInfo = 8;</code>
     * @return The bytes for reservedInfo.
     */
    public com.google.protobuf.ByteString
        getReservedInfoBytes() {
      Object ref = reservedInfo_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        reservedInfo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string reservedInfo = 8;</code>
     * @param value The reservedInfo to set.
     * @return This builder for chaining.
     */
    public Builder setReservedInfo(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      reservedInfo_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>optional string reservedInfo = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearReservedInfo() {
      reservedInfo_ = getDefaultInstance().getReservedInfo();
      bitField0_ = (bitField0_ & ~0x00000080);
      onChanged();
      return this;
    }
    /**
     * <code>optional string reservedInfo = 8;</code>
     * @param value The bytes for reservedInfo to set.
     * @return This builder for chaining.
     */
    public Builder setReservedInfoBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      reservedInfo_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:responseInfo)
  }

  // @@protoc_insertion_point(class_scope:responseInfo)
  private static final responseInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new responseInfo();
  }

  public static responseInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<responseInfo>
      PARSER = new com.google.protobuf.AbstractParser<responseInfo>() {
    @Override
    public responseInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<responseInfo> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<responseInfo> getParserForType() {
    return PARSER;
  }

  @Override
  public responseInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

