// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: service.proto
// Protobuf Java Version: 4.27.2

package com.yxf.serviceframe.entity;

public interface responseInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:responseInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required string reponseCode = 1;</code>
   * @return Whether the reponseCode field is set.
   */
  boolean hasReponseCode();
  /**
   * <code>required string reponseCode = 1;</code>
   * @return The reponseCode.
   */
  String getReponseCode();
  /**
   * <code>required string reponseCode = 1;</code>
   * @return The bytes for reponseCode.
   */
  com.google.protobuf.ByteString
      getReponseCodeBytes();

  /**
   * <code>optional string responseInfo = 2;</code>
   * @return Whether the responseInfo field is set.
   */
  boolean hasResponseInfo();
  /**
   * <code>optional string responseInfo = 2;</code>
   * @return The responseInfo.
   */
  String getResponseInfo();
  /**
   * <code>optional string responseInfo = 2;</code>
   * @return The bytes for responseInfo.
   */
  com.google.protobuf.ByteString
      getResponseInfoBytes();

  /**
   * <code>optional string highlight = 3;</code>
   * @return Whether the highlight field is set.
   */
  boolean hasHighlight();
  /**
   * <code>optional string highlight = 3;</code>
   * @return The highlight.
   */
  String getHighlight();
  /**
   * <code>optional string highlight = 3;</code>
   * @return The bytes for highlight.
   */
  com.google.protobuf.ByteString
      getHighlightBytes();

  /**
   * <code>required .RequestType ReType = 4 [default = SAMPLE];</code>
   * @return Whether the reType field is set.
   */
  boolean hasReType();
  /**
   * <code>required .RequestType ReType = 4 [default = SAMPLE];</code>
   * @return The reType.
   */
  RequestType getReType();

  /**
   * <code>required string sessionId = 5;</code>
   * @return Whether the sessionId field is set.
   */
  boolean hasSessionId();
  /**
   * <code>required string sessionId = 5;</code>
   * @return The sessionId.
   */
  String getSessionId();
  /**
   * <code>required string sessionId = 5;</code>
   * @return The bytes for sessionId.
   */
  com.google.protobuf.ByteString
      getSessionIdBytes();

  /**
   * <code>optional string userId = 6;</code>
   * @return Whether the userId field is set.
   */
  boolean hasUserId();
  /**
   * <code>optional string userId = 6;</code>
   * @return The userId.
   */
  String getUserId();
  /**
   * <code>optional string userId = 6;</code>
   * @return The bytes for userId.
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <code>repeated .responseInfo.itemInfo itemList = 7;</code>
   */
  java.util.List<responseInfo.itemInfo>
      getItemListList();
  /**
   * <code>repeated .responseInfo.itemInfo itemList = 7;</code>
   */
  responseInfo.itemInfo getItemList(int index);
  /**
   * <code>repeated .responseInfo.itemInfo itemList = 7;</code>
   */
  int getItemListCount();
  /**
   * <code>repeated .responseInfo.itemInfo itemList = 7;</code>
   */
  java.util.List<? extends responseInfo.itemInfoOrBuilder>
      getItemListOrBuilderList();
  /**
   * <code>repeated .responseInfo.itemInfo itemList = 7;</code>
   */
  responseInfo.itemInfoOrBuilder getItemListOrBuilder(
      int index);

  /**
   * <code>optional string reservedInfo = 8;</code>
   * @return Whether the reservedInfo field is set.
   */
  boolean hasReservedInfo();
  /**
   * <code>optional string reservedInfo = 8;</code>
   * @return The reservedInfo.
   */
  String getReservedInfo();
  /**
   * <code>optional string reservedInfo = 8;</code>
   * @return The bytes for reservedInfo.
   */
  com.google.protobuf.ByteString
      getReservedInfoBytes();
}
