// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: service.proto
// Protobuf Java Version: 4.27.2

package com.yxf.serviceframe.entity;

public final class Service {
  private Service() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 2,
      /* suffix= */ "",
      Service.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_requestInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_requestInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_responseInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_responseInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_responseInfo_itemInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_responseInfo_itemInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\rservice.proto\"\241\001\n\013requestInfo\022\021\n\treque" +
      "stId\030\001 \002(\t\022\023\n\013requestInfo\030\002 \001(\t\022\014\n\004info\030" +
      "\003 \002(\t\022$\n\006ReType\030\004 \001(\0162\014.RequestType:\006SAM" +
      "PLE\022\021\n\006userId\030\005 \001(\t:\0010\022\r\n\005devid\030\006 \001(\t\022\024\n" +
      "\014reservedInfo\030\007 \001(\t\"\314\002\n\014responseInfo\022\023\n\013" +
      "reponseCode\030\001 \002(\t\022\024\n\014responseInfo\030\002 \001(\t\022" +
      "\021\n\thighlight\030\003 \001(\t\022$\n\006ReType\030\004 \002(\0162\014.Req" +
      "uestType:\006SAMPLE\022\021\n\tsessionId\030\005 \002(\t\022\016\n\006u" +
      "serId\030\006 \001(\t\022(\n\010itemList\030\007 \003(\0132\026.response" +
      "Info.itemInfo\022\024\n\014reservedInfo\030\010 \001(\t\032X\n\010i" +
      "temInfo\022(\n\010itemType\030\001 \002(\0162\026.responseInfo" +
      ".itemType\022\016\n\006itemId\030\002 \002(\003\022\022\n\nitemFields\030" +
      "\003 \001(\t\"\033\n\010itemType\022\017\n\013SAMPLE_TYPE\020\000*\031\n\013Re" +
      "questType\022\n\n\006SAMPLE\020\00021\n\006Servce\022\'\n\006metho" +
      "d\022\014.requestInfo\032\r.responseInfo\"\000B\037\n\033com." +
      "yxf.serviceframe.entityP\001"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_requestInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_requestInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_requestInfo_descriptor,
        new String[] { "RequestId", "RequestInfo", "Info", "ReType", "UserId", "Devid", "ReservedInfo", });
    internal_static_responseInfo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_responseInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_responseInfo_descriptor,
        new String[] { "ReponseCode", "ResponseInfo", "Highlight", "ReType", "SessionId", "UserId", "ItemList", "ReservedInfo", });
    internal_static_responseInfo_itemInfo_descriptor =
      internal_static_responseInfo_descriptor.getNestedTypes().get(0);
    internal_static_responseInfo_itemInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_responseInfo_itemInfo_descriptor,
        new String[] { "ItemType", "ItemId", "ItemFields", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
